name: Build & Deploy

on:
  push:
    branches: [ "prod", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Create tarball of codebase
        run: tar -cf deploy.tar --exclude=deploy.tar .

      - name: Deploy App to CapRover (Production)
        if: github.ref == 'refs/heads/prod'
        uses: caprover/deploy-from-github@v1.0.1
        with:
            server: '${{ secrets.CAPROVER_SERVER_PROD }}'
            app: '${{ secrets.APP_NAME_PROD }}'
            token: '${{ secrets.APP_TOKEN_PROD }}'

      - name: Deploy App to CapRover (Development)
        if: github.ref == 'refs/heads/dev'
        uses: caprover/deploy-from-github@v1.0.1
        with:
            server: '${{ secrets.CAPROVER_SERVER_DEV }}'
            app: '${{ secrets.APP_NAME_DEV }}'
            token: '${{ secrets.APP_TOKEN_DEV }}'
